"""
Pydantic schemas used for:
  1. Structured LLM output (forces the model to return a predictable shape
     instead of free-form text we'd have to parse with regex).
  2. FastAPI request/response validation (auto-generates the OpenAPI docs
     and rejects malformed input before it reaches business logic).
"""
from __future__ import annotations
from typing import List, Optional
from pydantic import BaseModel, Field


# --------------------------------------------------------------------------
# Structured output contract for the LLM summarization step.
# The LLM ONLY ever fills in `summary_points` and `topic_tags` — every other
# field (title, url, source, published_date) is copied verbatim from the
# Tavily search result, never generated by the model. This is what keeps
# the article's factual metadata grounded in the search result rather than
# something the LLM could hallucinate.
# --------------------------------------------------------------------------
class ArticleSummarySchema(BaseModel):
    """What we ask the LLM to produce for a single article."""

    summary_points: List[str] = Field(
        description=(
            "3 to 5 short, concrete bullet points summarizing this specific "
            "article. Each bullet must be directly supported by the article "
            "content provided. Do not add outside facts, context, or "
            "speculation that is not present in the given text."
        ),
        min_length=1,
        max_length=6,
    )
    topic_tags: List[str] = Field(
        default_factory=list,
        description="1 to 3 short topic tags for the article, e.g. ['AI regulation', 'EU'].",
        max_length=3,
    )


class Article(BaseModel):
    """A single news article returned to the frontend."""

    rank: int
    title: str
    url: str
    source: str
    published_date: Optional[str] = "Unknown"
    raw_snippet: str = Field(description="Original content snippet returned by Tavily, pre-summarization.")
    summary_points: List[str]
    topic_tags: List[str] = Field(default_factory=list)
    summarized: bool = Field(
        default=True,
        description="False if the LLM summarization step failed for this article and raw_snippet is shown instead.",
    )


class NewsDigestResponse(BaseModel):
    """Top-level response for GET/POST /api/news."""

    query: str
    search_query_used: str
    article_count: int
    generated_at: str
    articles: List[Article]
    warnings: List[str] = Field(default_factory=list)


class NewsRequest(BaseModel):
    topic: Optional[str] = Field(
        default=None,
        description="Optional topic to focus the news search on, e.g. 'AI regulation' or 'space exploration'.",
        max_length=200,
    )
    max_articles: int = Field(default=10, ge=1, le=10)


class ErrorResponse(BaseModel):
    error: str
    detail: Optional[str] = None
